### ISSUE TITLE
Creating deployment with `Rmd` file can give Internal Server Error

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#2419]
With the name `example.Rmd` the creation fails, but with the name `static.Rmd` it succeeds.

Example R Markdown document:

```
---
title: "Content Session Token"
output: html_document
---

```{r}
print(Sys.getenv("CONNECT_CONTENT_SESSION_TOKEN"))
```
```

When creating the deployment it looks like when the file name is something other than `static.Rmd` we do not get prompted to select the type between `quarto` and `rmd` which is very odd. That may be causing the error down the line.

Slack context: https://positpbc.slack.com/archives/C05D7NZD52S/p1730920268909369

**Comment by dotNomad** [comment]
We also have the Posit Publisher output

<details>
  <summary>Output</summary>
  
>time=2024-11-06T14:21:56.479-05:00 level=ERROR msg="Internal server error" error="runtime error: invalid memory address or nil pointer dereference"
time=2024-11-06T14:21:56.479-05:00 level=DEBUG msg="Stacktrace for previous error" stack="goroutine 61 [running]:\ngithub.com/posit-dev/publisher/internal/services/api.NewService.newHTTPService.PanicRecovery.func2.1()\n\t/home/runner/work/publisher/publisher/internal/services/middleware/panic_recovery.go:17 +0x7c\npanic({0x104c0ef60?, 0x104fdd2c0?})\n\t/opt/hostedtoolcache/go/1.23.1/x64/src/runtime/panic.go:785 +0x124\ngithub.com/posit-dev/publisher/internal/services/api.applyFileAction(0x0, {0x140002136a0?, 0x140004d2be0?}, {0x14000027290, 0x29})\n\t/home/runner/work/publisher/publisher/internal/services/api/post_config_files.go:35 +0xd0\ngithub.com/posit-dev/publisher/internal/services/api.RouterHandlerFunc.PostConfigFilesHandlerFunc.func17({0x104ca14c0, 0x140003290c0}, 0x1400012ef00)\n\t/home/runner/work/publisher/publisher/internal/services/api/post_config_files.go:86 +0x1cc\nnet/http.HandlerFunc.ServeHTTP(0x1400012edc0?, {0x104ca14c0?, 0x140003290c0?}, 0x1400034edb0?)\n\t/opt/hostedtoolcache/go/1.23.1/x64/src/net/http/server.go:2220 +0x38\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0x140001ea300, {0x104ca14c0, 0x140003290c0}, 0x1400012ec80)\n\t/home/runner/work/publisher/publisher/vendor/github.com/gorilla/mux/mux.go:212 +0x194\ngithub.com/posit-dev/publisher/internal/services/api.RouterHandlerFunc.(*Cors).Handler.func26({0x104ca14c0, 0x140003290c0}, 0x1400012ec80)\n\t/home/runner/work/publisher/publisher/vendor/github.com/rs/cors/cors.go:289 +0x19c\nnet/http.HandlerFunc.ServeHTTP(0x104c9db40?, {0x104ca14c0?, 0x140003290c0?}, 0x140000b43c0?)\n\t/opt/hostedtoolcache/go/1.23.1/x64/src/net/http/server.go:2220 +0x38\ngithub.com/posit-dev/publisher/internal/services/api.NewService.newHTTPService.LogRequest.func1({0x104ca15f0, 0x140001681c0}, 0x1400012ec80)\n\t/home/runner/work/publisher/publisher/internal/services/middleware/log_request.go:93 +0xa0\ngithub.com/posit-dev/publisher/internal/services/api.NewService.newHTTPService.PanicRecovery.func2({0x104ca15f0?, 0x140001681c0?}, 0x0?)\n\t/home/runner/work/publisher/publisher/internal/services/middleware/panic_recovery.go:24 +0x6c\nnet/http.HandlerFunc.ServeHTTP(0x10?, {0x104ca15f0?,"

</details>

**Comment by dotNomad** [comment]
Took a look at this, and the error from the output may be a bit of a red hearing.

With some debugging I found that the Configuration that gets created from inspection doesn't have the entrypoint in the `files` field.

I'm still investigating, but in [`GetPossibleConfigs`](https://github.com/posit-dev/publisher/blob/0144cb4544da0eae6269fb59e50af8c96683e02f/internal/initialize/initialize.go#L189) I'm seeing the `typeDetector.InferType` give us back a config that looks like:

```json
{
  "comments": null,
  "$schema": "https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json",
  "type": "unknown",
  "validate": true,
  "hasParameters": false,
  "files": []
}
```

When we get to `normalizeConfig` there is nothing in `cfg.Files` and we try to add a `cfg.Entrypoint` but that doesn't exist in the config.

**Comment by dotNomad** [comment]
I'm thinking this may actually be two issues. It requires more investigation to be sure but

> When creating the deployment it looks like when the file name is something other than static.Rmd we do not get prompted to select the type between quarto and rmd which is very odd

Feels like it is separate from the error we are seeing in output, and the no entrypoint being set.
